name: CICD docker

on:
  push:
    branches:
    -  main

jobs:
    build-test-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: login to dockerhub
              uses: docker/login-action@v1
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build docker image
              uses: docker/build-push-action@v2
              with:
                    push: true
                    tags: pratik0078/webapp:${{ github.sha }}
                    file: Dockerfile  

            - name: Deploy to ec2 instance
              run: sudo docker pull pratik0078/webapp:latest
            - name: Delete Old docker container
              run: sudo docker rm -f webapp || true
            - name: Run Docker Container
              run: sudo docker run -d -p 8080:8080 --name webapp-container pratik0078/webapp
