name: CICD docker

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pratik0078/cicd-pipeline:latest
          file: Dockerfile  

  deploy_job:
    runs-on: self-hosted
    needs: build_job
    steps:
      - name: Deploy to EC2 instance
        run: sudo docker pull pratik0078/cicd-pipeline:latest

      - name: Delete old Docker container
        run: sudo docker rm -f cicd-pipeline-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:80 --name cicd-pipeline-container pratik0078/cicd-pipeline

      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'success,failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
