name: CICD docker

on:
  push:
    branches:
    -  main

jobs:
    build-test-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: login to dockerhub
              uses: docker/login-action@v1
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build docker image
              uses: docker/build-push-action@v2
              with:
                    push: true
                    tags: pratik0078/webapp:${{ github.sha }}
                    file: Dockerfile  

            - name: Deploy to ec2 instance
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                    docker stop webapp || true
                    docker rm webapp || true
                    docker rmi pratik0078/webapp:${{ github.sha }} || true
                    docker pull pratik0078/webapp:${{ github.sha }}
                    docker run -d --name webapp -p 80:80 pratik0078/webapp:${{ github.sha }}
                    
